#!/bin/bash
# scripts/generate-client-safe.sh
set -e

echo "🚀 Smart Client Generation"
echo "=========================="

# Get absolute paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLIENT_DIR="$PROJECT_ROOT/src/client"
BACKUP_DIR="/tmp/client-full-backup-$(date +%s)"

echo "📁 Project root: $PROJECT_ROOT"
echo "📁 Client dir: $CLIENT_DIR"

# Check if backend is running
echo ""
echo "🔍 Checking if backend is running..."
if ! curl -s http://localhost:8000/api/v1/openapi.json > /dev/null; then
  echo "❌ Backend is not running at http://localhost:8000"
  echo "   Please start the backend first"
  exit 1
fi
echo "✅ Backend is running"

# Download OpenAPI spec to temp file
OPENAPI_FILE="/tmp/openapi-$(date +%s).json"
echo ""
echo "📥 Downloading OpenAPI spec..."
curl -s http://localhost:8000/api/v1/openapi.json > "$OPENAPI_FILE"

if [ ! -s "$OPENAPI_FILE" ]; then
  echo "❌ Failed to download OpenAPI spec"
  rm "$OPENAPI_FILE"
  exit 1
fi
echo "✅ OpenAPI spec downloaded"

# Check if client folder exists
if [ ! -d "$CLIENT_DIR" ]; then
  echo ""
  echo "📁 No client folder found. Generating fresh..."
  npx openapi-typescript-codegen \
    --input "$OPENAPI_FILE" \
    --output "$CLIENT_DIR" \
    --client axios \
    --useOptions \
    --useUnionTypes \
    --exportSchemas true \
    --exportServices true \
    --exportModels true
  rm "$OPENAPI_FILE"
  echo "✅ Fresh client generated!"
  exit 0
fi

# Backup ALL files
echo ""
echo "📦 Backing up entire client folder..."
cp -r "$CLIENT_DIR" "$BACKUP_DIR"
echo "   Backup saved to: $BACKUP_DIR"

# Generate new version in temporary location
echo ""
echo "⚙️ Generating new client..."
CLIENT_NEW="$CLIENT_DIR-new"
npx openapi-typescript-codegen \
  --input "$OPENAPI_FILE" \
  --output "$CLIENT_NEW" \
  --client axios \
  --useOptions \
  --useUnionTypes \
  --exportSchemas true \
  --exportServices true \
  --exportModels true

# Clean up temp OpenAPI file
rm "$OPENAPI_FILE"

# Smart merge: Restore user-modified files
echo ""
echo "🔄 Merging changes (preserving user modifications)..."

# 1. Restore core folder if it exists (user modifications)
if [ -d "$BACKUP_DIR/core" ]; then
  echo "   ↩️  Restoring core folder..."
  rm -rf "$CLIENT_NEW/core"
  cp -r "$BACKUP_DIR/core" "$CLIENT_NEW/"
fi

# 2. Restore specific user files
USER_FILES=("OpenAPI.ts")
for filename in "${USER_FILES[@]}"; do
  if [ -f "$BACKUP_DIR/$filename" ]; then
    echo "   ↩️  Restoring $filename..."
    cp "$BACKUP_DIR/$filename" "$CLIENT_NEW/"
  fi
done

# 3. Restore any custom folders (not generated by openapi-typescript-codegen)
for dir in "$BACKUP_DIR"/*; do
  if [ -d "$dir" ]; then
    dirname=$(basename "$dir")
    # Skip generated folders
    if [[ "$dirname" != "models" && "$dirname" != "services" && "$dirname" != "schemas" && "$dirname" != "core" ]]; then
      echo "   ↩️  Restoring custom folder: $dirname..."
      cp -r "$dir" "$CLIENT_NEW/"
    fi
  fi
done

# Replace old with new
echo ""
echo "🔄 Replacing old client with new..."
rm -rf "$CLIENT_DIR"
mv "$CLIENT_NEW" "$CLIENT_DIR"

# Success
echo ""
echo "════════════════════════════════════════"
echo "✅ Client Generation Complete!"
echo "════════════════════════════════════════"
echo ""
echo "📝 Generated files:"
if [ -d "$CLIENT_DIR/services" ]; then
  echo "   Services: $(ls "$CLIENT_DIR/services" | wc -l) files"
fi
if [ -d "$CLIENT_DIR/models" ]; then
  echo "   Models: $(ls "$CLIENT_DIR/models" | wc -l) files"
fi
if [ -d "$CLIENT_DIR/core" ]; then
  echo "   Core: $(ls "$CLIENT_DIR/core" | wc -l) files (preserved)"
fi
echo ""
echo "📝 Next steps:"
echo "   1. Check changes: git diff src/client"
echo "   2. Test your app: npm run dev"
echo "   3. Full backup at: $BACKUP_DIR"
echo ""
echo "💡 If any files are missing, restore with:"
echo "   cp -r \"$BACKUP_DIR/path/to/file\" \"$CLIENT_DIR/\""