"""add competition_baseline_score

Revision ID: 764894db5fec
Revises: f1d7f0ef8cb8
Create Date: 2026-04-12 15:10:39.531191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '764894db5fec'
down_revision: Union[str, Sequence[str], None] = 'f1d7f0ef8cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crackmode_profiles', sa.Column('competition_baseline_score', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crackmode_profiles', 'competition_baseline_score')
    # ### end Alembic commands ###
