"""Rename global_rank to rank

Revision ID: 7ae0881d75cb
Revises: 5d81a0f90b0f
Create Date: 2026-02-12 08:47:32.512771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '7ae0881d75cb'
down_revision: Union[str, Sequence[str], None] = '5d81a0f90b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crackmode_profiles', 'global_rank', new_column_name='rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crackmode_profiles', 'rank', new_column_name='global_rank')
    # ### end Alembic commands ###
