"""Create Crackmode User and ProfileModels

Revision ID: e485963d1722
Revises: 
Create Date: 2026-02-09 06:54:49.653542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'e485963d1722'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('crackmode_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leetcode_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('global_rank', sa.Integer(), nullable=False),
    sa.Column('division_rank', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('difficulty_points', sa.Integer(), nullable=False),
    sa.Column('streak_bonus', sa.Integer(), nullable=False),
    sa.Column('weekly_bonus', sa.Integer(), nullable=False),
    sa.Column('contest_bonus', sa.Integer(), nullable=False),
    sa.Column('total_easy', sa.Integer(), nullable=False),
    sa.Column('total_medium', sa.Integer(), nullable=False),
    sa.Column('total_hard', sa.Integer(), nullable=False),
    sa.Column('total_problems_solved', sa.Integer(), nullable=False),
    sa.Column('contest_rating', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('weekly_solves', sa.Integer(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=False),
    sa.Column('sync_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crackmode_profiles_leetcode_username'), 'crackmode_profiles', ['leetcode_username'], unique=True)
    op.create_index(op.f('ix_crackmode_profiles_user_id'), 'crackmode_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crackmode_profiles_user_id'), table_name='crackmode_profiles')
    op.drop_index(op.f('ix_crackmode_profiles_leetcode_username'), table_name='crackmode_profiles')
    op.drop_table('crackmode_profiles')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
