/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutDocsIndexRouteImport } from './routes/_layout/docs/index'
import { Route as LayoutDocsLayoutRouteImport } from './routes/_layout/docs/_layout'
import { Route as LayoutDocsLeetcode75IndexRouteImport } from './routes/_layout/docs/leetcode75/index'
import { Route as LayoutDocsIntroductionIndexRouteImport } from './routes/_layout/docs/introduction/index'
import { Route as LayoutDocsProblemsValidParenthesesRouteImport } from './routes/_layout/docs/problems/valid-parentheses'
import { Route as LayoutDocsProblemsUniqueNumberOfOccurrencesRouteImport } from './routes/_layout/docs/problems/unique-number-of-occurrences'
import { Route as LayoutDocsProblemsTwoSumRouteImport } from './routes/_layout/docs/problems/two-sum'
import { Route as LayoutDocsProblemsNumberOfGoodPairsRouteImport } from './routes/_layout/docs/problems/number-of-good-pairs'
import { Route as LayoutDocsProblemsNumberOf1BitsRouteImport } from './routes/_layout/docs/problems/number-of-1-bits'
import { Route as LayoutDocsProblemsMostCommonWordRouteImport } from './routes/_layout/docs/problems/most-common-word'
import { Route as LayoutDocsProblemsMissingNumberRouteImport } from './routes/_layout/docs/problems/missing-number'
import { Route as LayoutDocsProblemsMergeSortedArrayRouteImport } from './routes/_layout/docs/problems/merge-sorted-array'
import { Route as LayoutDocsProblemsLongestPalindromeRouteImport } from './routes/_layout/docs/problems/longest-palindrome'
import { Route as LayoutDocsProblemsLongestConsecutiveSequenceRouteImport } from './routes/_layout/docs/problems/longest-consecutive-sequence'
import { Route as LayoutDocsProblemsImplementStackUsingQueuesRouteImport } from './routes/_layout/docs/problems/implement-stack-using-queues'
import { Route as LayoutDocsProblemsFindTheDifferenceOfTwoArraysRouteImport } from './routes/_layout/docs/problems/find-the-difference-of-two-arrays'
import { Route as LayoutDocsProblemsFindTheDifferenceRouteImport } from './routes/_layout/docs/problems/find-the-difference'
import { Route as LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRouteImport } from './routes/_layout/docs/problems/find-all-numbers-disappeared-in-an-array'
import { Route as LayoutDocsProblemsFindAllDuplicatesInAnArrayRouteImport } from './routes/_layout/docs/problems/find-all-duplicates-in-an-array'
import { Route as LayoutDocsProblemsDistributeCandiesRouteImport } from './routes/_layout/docs/problems/distribute-candies'
import { Route as LayoutDocsProblemsDetermineIfTwoStringsAreCloseRouteImport } from './routes/_layout/docs/problems/determine-if-two-strings-are-close'
import { Route as LayoutDocsProblemsContainsDuplicateRouteImport } from './routes/_layout/docs/problems/contains-duplicate'
import { Route as LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRouteImport } from './routes/_layout/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
import { Route as LayoutDocsProblemsBestTimeToBuyAndSellStockRouteImport } from './routes/_layout/docs/problems/best-time-to-buy-and-sell-stock'
import { Route as LayoutDocsProblemsAsteroidCollisionRouteImport } from './routes/_layout/docs/problems/asteroid-collision'
import { Route as LayoutDocsLeetcode75ArraysStringsIndexRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/index'
import { Route as LayoutDocsLeetcode75ArraysStringsStringCompressionRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/string-compression'
import { Route as LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/product-of-array-except-self'
import { Route as LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/merge-strings-alternately'
import { Route as LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
import { Route as LayoutDocsLeetcode75ArraysStringsIntroductionRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/introduction'
import { Route as LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
import { Route as LayoutDocsLeetcode75ArraysStringsGcdOfStringsRouteImport } from './routes/_layout/docs/leetcode75/arrays-strings/gcd-of-strings'

const LayoutDocsRouteImport = createFileRoute('/_layout/docs')()

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDocsRoute = LayoutDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDocsIndexRoute = LayoutDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDocsRoute,
} as any)
const LayoutDocsLayoutRoute = LayoutDocsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutDocsRoute,
} as any)
const LayoutDocsLeetcode75IndexRoute =
  LayoutDocsLeetcode75IndexRouteImport.update({
    id: '/leetcode75/',
    path: '/leetcode75/',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsIntroductionIndexRoute =
  LayoutDocsIntroductionIndexRouteImport.update({
    id: '/introduction/',
    path: '/introduction/',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsValidParenthesesRoute =
  LayoutDocsProblemsValidParenthesesRouteImport.update({
    id: '/problems/valid-parentheses',
    path: '/problems/valid-parentheses',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsUniqueNumberOfOccurrencesRoute =
  LayoutDocsProblemsUniqueNumberOfOccurrencesRouteImport.update({
    id: '/problems/unique-number-of-occurrences',
    path: '/problems/unique-number-of-occurrences',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsTwoSumRoute =
  LayoutDocsProblemsTwoSumRouteImport.update({
    id: '/problems/two-sum',
    path: '/problems/two-sum',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsNumberOfGoodPairsRoute =
  LayoutDocsProblemsNumberOfGoodPairsRouteImport.update({
    id: '/problems/number-of-good-pairs',
    path: '/problems/number-of-good-pairs',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsNumberOf1BitsRoute =
  LayoutDocsProblemsNumberOf1BitsRouteImport.update({
    id: '/problems/number-of-1-bits',
    path: '/problems/number-of-1-bits',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsMostCommonWordRoute =
  LayoutDocsProblemsMostCommonWordRouteImport.update({
    id: '/problems/most-common-word',
    path: '/problems/most-common-word',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsMissingNumberRoute =
  LayoutDocsProblemsMissingNumberRouteImport.update({
    id: '/problems/missing-number',
    path: '/problems/missing-number',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsMergeSortedArrayRoute =
  LayoutDocsProblemsMergeSortedArrayRouteImport.update({
    id: '/problems/merge-sorted-array',
    path: '/problems/merge-sorted-array',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsLongestPalindromeRoute =
  LayoutDocsProblemsLongestPalindromeRouteImport.update({
    id: '/problems/longest-palindrome',
    path: '/problems/longest-palindrome',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsLongestConsecutiveSequenceRoute =
  LayoutDocsProblemsLongestConsecutiveSequenceRouteImport.update({
    id: '/problems/longest-consecutive-sequence',
    path: '/problems/longest-consecutive-sequence',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsImplementStackUsingQueuesRoute =
  LayoutDocsProblemsImplementStackUsingQueuesRouteImport.update({
    id: '/problems/implement-stack-using-queues',
    path: '/problems/implement-stack-using-queues',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute =
  LayoutDocsProblemsFindTheDifferenceOfTwoArraysRouteImport.update({
    id: '/problems/find-the-difference-of-two-arrays',
    path: '/problems/find-the-difference-of-two-arrays',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsFindTheDifferenceRoute =
  LayoutDocsProblemsFindTheDifferenceRouteImport.update({
    id: '/problems/find-the-difference',
    path: '/problems/find-the-difference',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute =
  LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRouteImport.update({
    id: '/problems/find-all-numbers-disappeared-in-an-array',
    path: '/problems/find-all-numbers-disappeared-in-an-array',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute =
  LayoutDocsProblemsFindAllDuplicatesInAnArrayRouteImport.update({
    id: '/problems/find-all-duplicates-in-an-array',
    path: '/problems/find-all-duplicates-in-an-array',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsDistributeCandiesRoute =
  LayoutDocsProblemsDistributeCandiesRouteImport.update({
    id: '/problems/distribute-candies',
    path: '/problems/distribute-candies',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute =
  LayoutDocsProblemsDetermineIfTwoStringsAreCloseRouteImport.update({
    id: '/problems/determine-if-two-strings-are-close',
    path: '/problems/determine-if-two-strings-are-close',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsContainsDuplicateRoute =
  LayoutDocsProblemsContainsDuplicateRouteImport.update({
    id: '/problems/contains-duplicate',
    path: '/problems/contains-duplicate',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute =
  LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRouteImport.update(
    {
      id: '/problems/check-if-number-has-equal-digit-count-and-digit-value',
      path: '/problems/check-if-number-has-equal-digit-count-and-digit-value',
      getParentRoute: () => LayoutDocsRoute,
    } as any,
  )
const LayoutDocsProblemsBestTimeToBuyAndSellStockRoute =
  LayoutDocsProblemsBestTimeToBuyAndSellStockRouteImport.update({
    id: '/problems/best-time-to-buy-and-sell-stock',
    path: '/problems/best-time-to-buy-and-sell-stock',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsProblemsAsteroidCollisionRoute =
  LayoutDocsProblemsAsteroidCollisionRouteImport.update({
    id: '/problems/asteroid-collision',
    path: '/problems/asteroid-collision',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsLeetcode75ArraysStringsIndexRoute =
  LayoutDocsLeetcode75ArraysStringsIndexRouteImport.update({
    id: '/leetcode75/arrays-strings/',
    path: '/leetcode75/arrays-strings/',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsLeetcode75ArraysStringsStringCompressionRoute =
  LayoutDocsLeetcode75ArraysStringsStringCompressionRouteImport.update({
    id: '/leetcode75/arrays-strings/string-compression',
    path: '/leetcode75/arrays-strings/string-compression',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute =
  LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRouteImport.update({
    id: '/leetcode75/arrays-strings/product-of-array-except-self',
    path: '/leetcode75/arrays-strings/product-of-array-except-self',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute =
  LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRouteImport.update({
    id: '/leetcode75/arrays-strings/merge-strings-alternately',
    path: '/leetcode75/arrays-strings/merge-strings-alternately',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute =
  LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRouteImport.update({
    id: '/leetcode75/arrays-strings/kids-with-greatest-candies',
    path: '/leetcode75/arrays-strings/kids-with-greatest-candies',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsLeetcode75ArraysStringsIntroductionRoute =
  LayoutDocsLeetcode75ArraysStringsIntroductionRouteImport.update({
    id: '/leetcode75/arrays-strings/introduction',
    path: '/leetcode75/arrays-strings/introduction',
    getParentRoute: () => LayoutDocsRoute,
  } as any)
const LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute =
  LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRouteImport.update(
    {
      id: '/leetcode75/arrays-strings/increasing-triplet-subsequence',
      path: '/leetcode75/arrays-strings/increasing-triplet-subsequence',
      getParentRoute: () => LayoutDocsRoute,
    } as any,
  )
const LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute =
  LayoutDocsLeetcode75ArraysStringsGcdOfStringsRouteImport.update({
    id: '/leetcode75/arrays-strings/gcd-of-strings',
    path: '/leetcode75/arrays-strings/gcd-of-strings',
    getParentRoute: () => LayoutDocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs': typeof LayoutDocsLayoutRoute
  '/docs/': typeof LayoutDocsIndexRoute
  '/docs/problems/asteroid-collision': typeof LayoutDocsProblemsAsteroidCollisionRoute
  '/docs/problems/best-time-to-buy-and-sell-stock': typeof LayoutDocsProblemsBestTimeToBuyAndSellStockRoute
  '/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': typeof LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  '/docs/problems/contains-duplicate': typeof LayoutDocsProblemsContainsDuplicateRoute
  '/docs/problems/determine-if-two-strings-are-close': typeof LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute
  '/docs/problems/distribute-candies': typeof LayoutDocsProblemsDistributeCandiesRoute
  '/docs/problems/find-all-duplicates-in-an-array': typeof LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute
  '/docs/problems/find-all-numbers-disappeared-in-an-array': typeof LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  '/docs/problems/find-the-difference': typeof LayoutDocsProblemsFindTheDifferenceRoute
  '/docs/problems/find-the-difference-of-two-arrays': typeof LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute
  '/docs/problems/implement-stack-using-queues': typeof LayoutDocsProblemsImplementStackUsingQueuesRoute
  '/docs/problems/longest-consecutive-sequence': typeof LayoutDocsProblemsLongestConsecutiveSequenceRoute
  '/docs/problems/longest-palindrome': typeof LayoutDocsProblemsLongestPalindromeRoute
  '/docs/problems/merge-sorted-array': typeof LayoutDocsProblemsMergeSortedArrayRoute
  '/docs/problems/missing-number': typeof LayoutDocsProblemsMissingNumberRoute
  '/docs/problems/most-common-word': typeof LayoutDocsProblemsMostCommonWordRoute
  '/docs/problems/number-of-1-bits': typeof LayoutDocsProblemsNumberOf1BitsRoute
  '/docs/problems/number-of-good-pairs': typeof LayoutDocsProblemsNumberOfGoodPairsRoute
  '/docs/problems/two-sum': typeof LayoutDocsProblemsTwoSumRoute
  '/docs/problems/unique-number-of-occurrences': typeof LayoutDocsProblemsUniqueNumberOfOccurrencesRoute
  '/docs/problems/valid-parentheses': typeof LayoutDocsProblemsValidParenthesesRoute
  '/docs/introduction': typeof LayoutDocsIntroductionIndexRoute
  '/docs/leetcode75': typeof LayoutDocsLeetcode75IndexRoute
  '/docs/leetcode75/arrays-strings/gcd-of-strings': typeof LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute
  '/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': typeof LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  '/docs/leetcode75/arrays-strings/introduction': typeof LayoutDocsLeetcode75ArraysStringsIntroductionRoute
  '/docs/leetcode75/arrays-strings/kids-with-greatest-candies': typeof LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  '/docs/leetcode75/arrays-strings/merge-strings-alternately': typeof LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  '/docs/leetcode75/arrays-strings/product-of-array-except-self': typeof LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  '/docs/leetcode75/arrays-strings/string-compression': typeof LayoutDocsLeetcode75ArraysStringsStringCompressionRoute
  '/docs/leetcode75/arrays-strings': typeof LayoutDocsLeetcode75ArraysStringsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs': typeof LayoutDocsIndexRoute
  '/docs/problems/asteroid-collision': typeof LayoutDocsProblemsAsteroidCollisionRoute
  '/docs/problems/best-time-to-buy-and-sell-stock': typeof LayoutDocsProblemsBestTimeToBuyAndSellStockRoute
  '/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': typeof LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  '/docs/problems/contains-duplicate': typeof LayoutDocsProblemsContainsDuplicateRoute
  '/docs/problems/determine-if-two-strings-are-close': typeof LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute
  '/docs/problems/distribute-candies': typeof LayoutDocsProblemsDistributeCandiesRoute
  '/docs/problems/find-all-duplicates-in-an-array': typeof LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute
  '/docs/problems/find-all-numbers-disappeared-in-an-array': typeof LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  '/docs/problems/find-the-difference': typeof LayoutDocsProblemsFindTheDifferenceRoute
  '/docs/problems/find-the-difference-of-two-arrays': typeof LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute
  '/docs/problems/implement-stack-using-queues': typeof LayoutDocsProblemsImplementStackUsingQueuesRoute
  '/docs/problems/longest-consecutive-sequence': typeof LayoutDocsProblemsLongestConsecutiveSequenceRoute
  '/docs/problems/longest-palindrome': typeof LayoutDocsProblemsLongestPalindromeRoute
  '/docs/problems/merge-sorted-array': typeof LayoutDocsProblemsMergeSortedArrayRoute
  '/docs/problems/missing-number': typeof LayoutDocsProblemsMissingNumberRoute
  '/docs/problems/most-common-word': typeof LayoutDocsProblemsMostCommonWordRoute
  '/docs/problems/number-of-1-bits': typeof LayoutDocsProblemsNumberOf1BitsRoute
  '/docs/problems/number-of-good-pairs': typeof LayoutDocsProblemsNumberOfGoodPairsRoute
  '/docs/problems/two-sum': typeof LayoutDocsProblemsTwoSumRoute
  '/docs/problems/unique-number-of-occurrences': typeof LayoutDocsProblemsUniqueNumberOfOccurrencesRoute
  '/docs/problems/valid-parentheses': typeof LayoutDocsProblemsValidParenthesesRoute
  '/docs/introduction': typeof LayoutDocsIntroductionIndexRoute
  '/docs/leetcode75': typeof LayoutDocsLeetcode75IndexRoute
  '/docs/leetcode75/arrays-strings/gcd-of-strings': typeof LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute
  '/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': typeof LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  '/docs/leetcode75/arrays-strings/introduction': typeof LayoutDocsLeetcode75ArraysStringsIntroductionRoute
  '/docs/leetcode75/arrays-strings/kids-with-greatest-candies': typeof LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  '/docs/leetcode75/arrays-strings/merge-strings-alternately': typeof LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  '/docs/leetcode75/arrays-strings/product-of-array-except-self': typeof LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  '/docs/leetcode75/arrays-strings/string-compression': typeof LayoutDocsLeetcode75ArraysStringsStringCompressionRoute
  '/docs/leetcode75/arrays-strings': typeof LayoutDocsLeetcode75ArraysStringsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/docs': typeof LayoutDocsRouteWithChildren
  '/_layout/docs/_layout': typeof LayoutDocsLayoutRoute
  '/_layout/docs/': typeof LayoutDocsIndexRoute
  '/_layout/docs/problems/asteroid-collision': typeof LayoutDocsProblemsAsteroidCollisionRoute
  '/_layout/docs/problems/best-time-to-buy-and-sell-stock': typeof LayoutDocsProblemsBestTimeToBuyAndSellStockRoute
  '/_layout/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': typeof LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  '/_layout/docs/problems/contains-duplicate': typeof LayoutDocsProblemsContainsDuplicateRoute
  '/_layout/docs/problems/determine-if-two-strings-are-close': typeof LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute
  '/_layout/docs/problems/distribute-candies': typeof LayoutDocsProblemsDistributeCandiesRoute
  '/_layout/docs/problems/find-all-duplicates-in-an-array': typeof LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute
  '/_layout/docs/problems/find-all-numbers-disappeared-in-an-array': typeof LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  '/_layout/docs/problems/find-the-difference': typeof LayoutDocsProblemsFindTheDifferenceRoute
  '/_layout/docs/problems/find-the-difference-of-two-arrays': typeof LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute
  '/_layout/docs/problems/implement-stack-using-queues': typeof LayoutDocsProblemsImplementStackUsingQueuesRoute
  '/_layout/docs/problems/longest-consecutive-sequence': typeof LayoutDocsProblemsLongestConsecutiveSequenceRoute
  '/_layout/docs/problems/longest-palindrome': typeof LayoutDocsProblemsLongestPalindromeRoute
  '/_layout/docs/problems/merge-sorted-array': typeof LayoutDocsProblemsMergeSortedArrayRoute
  '/_layout/docs/problems/missing-number': typeof LayoutDocsProblemsMissingNumberRoute
  '/_layout/docs/problems/most-common-word': typeof LayoutDocsProblemsMostCommonWordRoute
  '/_layout/docs/problems/number-of-1-bits': typeof LayoutDocsProblemsNumberOf1BitsRoute
  '/_layout/docs/problems/number-of-good-pairs': typeof LayoutDocsProblemsNumberOfGoodPairsRoute
  '/_layout/docs/problems/two-sum': typeof LayoutDocsProblemsTwoSumRoute
  '/_layout/docs/problems/unique-number-of-occurrences': typeof LayoutDocsProblemsUniqueNumberOfOccurrencesRoute
  '/_layout/docs/problems/valid-parentheses': typeof LayoutDocsProblemsValidParenthesesRoute
  '/_layout/docs/introduction/': typeof LayoutDocsIntroductionIndexRoute
  '/_layout/docs/leetcode75/': typeof LayoutDocsLeetcode75IndexRoute
  '/_layout/docs/leetcode75/arrays-strings/gcd-of-strings': typeof LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute
  '/_layout/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': typeof LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  '/_layout/docs/leetcode75/arrays-strings/introduction': typeof LayoutDocsLeetcode75ArraysStringsIntroductionRoute
  '/_layout/docs/leetcode75/arrays-strings/kids-with-greatest-candies': typeof LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  '/_layout/docs/leetcode75/arrays-strings/merge-strings-alternately': typeof LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  '/_layout/docs/leetcode75/arrays-strings/product-of-array-except-self': typeof LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  '/_layout/docs/leetcode75/arrays-strings/string-compression': typeof LayoutDocsLeetcode75ArraysStringsStringCompressionRoute
  '/_layout/docs/leetcode75/arrays-strings/': typeof LayoutDocsLeetcode75ArraysStringsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/auth/callback'
    | '/docs'
    | '/docs/'
    | '/docs/problems/asteroid-collision'
    | '/docs/problems/best-time-to-buy-and-sell-stock'
    | '/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
    | '/docs/problems/contains-duplicate'
    | '/docs/problems/determine-if-two-strings-are-close'
    | '/docs/problems/distribute-candies'
    | '/docs/problems/find-all-duplicates-in-an-array'
    | '/docs/problems/find-all-numbers-disappeared-in-an-array'
    | '/docs/problems/find-the-difference'
    | '/docs/problems/find-the-difference-of-two-arrays'
    | '/docs/problems/implement-stack-using-queues'
    | '/docs/problems/longest-consecutive-sequence'
    | '/docs/problems/longest-palindrome'
    | '/docs/problems/merge-sorted-array'
    | '/docs/problems/missing-number'
    | '/docs/problems/most-common-word'
    | '/docs/problems/number-of-1-bits'
    | '/docs/problems/number-of-good-pairs'
    | '/docs/problems/two-sum'
    | '/docs/problems/unique-number-of-occurrences'
    | '/docs/problems/valid-parentheses'
    | '/docs/introduction'
    | '/docs/leetcode75'
    | '/docs/leetcode75/arrays-strings/gcd-of-strings'
    | '/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
    | '/docs/leetcode75/arrays-strings/introduction'
    | '/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
    | '/docs/leetcode75/arrays-strings/merge-strings-alternately'
    | '/docs/leetcode75/arrays-strings/product-of-array-except-self'
    | '/docs/leetcode75/arrays-strings/string-compression'
    | '/docs/leetcode75/arrays-strings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/auth/callback'
    | '/docs'
    | '/docs/problems/asteroid-collision'
    | '/docs/problems/best-time-to-buy-and-sell-stock'
    | '/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
    | '/docs/problems/contains-duplicate'
    | '/docs/problems/determine-if-two-strings-are-close'
    | '/docs/problems/distribute-candies'
    | '/docs/problems/find-all-duplicates-in-an-array'
    | '/docs/problems/find-all-numbers-disappeared-in-an-array'
    | '/docs/problems/find-the-difference'
    | '/docs/problems/find-the-difference-of-two-arrays'
    | '/docs/problems/implement-stack-using-queues'
    | '/docs/problems/longest-consecutive-sequence'
    | '/docs/problems/longest-palindrome'
    | '/docs/problems/merge-sorted-array'
    | '/docs/problems/missing-number'
    | '/docs/problems/most-common-word'
    | '/docs/problems/number-of-1-bits'
    | '/docs/problems/number-of-good-pairs'
    | '/docs/problems/two-sum'
    | '/docs/problems/unique-number-of-occurrences'
    | '/docs/problems/valid-parentheses'
    | '/docs/introduction'
    | '/docs/leetcode75'
    | '/docs/leetcode75/arrays-strings/gcd-of-strings'
    | '/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
    | '/docs/leetcode75/arrays-strings/introduction'
    | '/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
    | '/docs/leetcode75/arrays-strings/merge-strings-alternately'
    | '/docs/leetcode75/arrays-strings/product-of-array-except-self'
    | '/docs/leetcode75/arrays-strings/string-compression'
    | '/docs/leetcode75/arrays-strings'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/auth/callback'
    | '/_layout/docs'
    | '/_layout/docs/_layout'
    | '/_layout/docs/'
    | '/_layout/docs/problems/asteroid-collision'
    | '/_layout/docs/problems/best-time-to-buy-and-sell-stock'
    | '/_layout/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
    | '/_layout/docs/problems/contains-duplicate'
    | '/_layout/docs/problems/determine-if-two-strings-are-close'
    | '/_layout/docs/problems/distribute-candies'
    | '/_layout/docs/problems/find-all-duplicates-in-an-array'
    | '/_layout/docs/problems/find-all-numbers-disappeared-in-an-array'
    | '/_layout/docs/problems/find-the-difference'
    | '/_layout/docs/problems/find-the-difference-of-two-arrays'
    | '/_layout/docs/problems/implement-stack-using-queues'
    | '/_layout/docs/problems/longest-consecutive-sequence'
    | '/_layout/docs/problems/longest-palindrome'
    | '/_layout/docs/problems/merge-sorted-array'
    | '/_layout/docs/problems/missing-number'
    | '/_layout/docs/problems/most-common-word'
    | '/_layout/docs/problems/number-of-1-bits'
    | '/_layout/docs/problems/number-of-good-pairs'
    | '/_layout/docs/problems/two-sum'
    | '/_layout/docs/problems/unique-number-of-occurrences'
    | '/_layout/docs/problems/valid-parentheses'
    | '/_layout/docs/introduction/'
    | '/_layout/docs/leetcode75/'
    | '/_layout/docs/leetcode75/arrays-strings/gcd-of-strings'
    | '/_layout/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
    | '/_layout/docs/leetcode75/arrays-strings/introduction'
    | '/_layout/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
    | '/_layout/docs/leetcode75/arrays-strings/merge-strings-alternately'
    | '/_layout/docs/leetcode75/arrays-strings/product-of-array-except-self'
    | '/_layout/docs/leetcode75/arrays-strings/string-compression'
    | '/_layout/docs/leetcode75/arrays-strings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/docs': {
      id: '/_layout/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof LayoutDocsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/docs/': {
      id: '/_layout/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof LayoutDocsIndexRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/_layout': {
      id: '/_layout/docs/_layout'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof LayoutDocsLayoutRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/': {
      id: '/_layout/docs/leetcode75/'
      path: '/leetcode75'
      fullPath: '/docs/leetcode75'
      preLoaderRoute: typeof LayoutDocsLeetcode75IndexRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/introduction/': {
      id: '/_layout/docs/introduction/'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof LayoutDocsIntroductionIndexRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/valid-parentheses': {
      id: '/_layout/docs/problems/valid-parentheses'
      path: '/problems/valid-parentheses'
      fullPath: '/docs/problems/valid-parentheses'
      preLoaderRoute: typeof LayoutDocsProblemsValidParenthesesRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/unique-number-of-occurrences': {
      id: '/_layout/docs/problems/unique-number-of-occurrences'
      path: '/problems/unique-number-of-occurrences'
      fullPath: '/docs/problems/unique-number-of-occurrences'
      preLoaderRoute: typeof LayoutDocsProblemsUniqueNumberOfOccurrencesRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/two-sum': {
      id: '/_layout/docs/problems/two-sum'
      path: '/problems/two-sum'
      fullPath: '/docs/problems/two-sum'
      preLoaderRoute: typeof LayoutDocsProblemsTwoSumRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/number-of-good-pairs': {
      id: '/_layout/docs/problems/number-of-good-pairs'
      path: '/problems/number-of-good-pairs'
      fullPath: '/docs/problems/number-of-good-pairs'
      preLoaderRoute: typeof LayoutDocsProblemsNumberOfGoodPairsRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/number-of-1-bits': {
      id: '/_layout/docs/problems/number-of-1-bits'
      path: '/problems/number-of-1-bits'
      fullPath: '/docs/problems/number-of-1-bits'
      preLoaderRoute: typeof LayoutDocsProblemsNumberOf1BitsRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/most-common-word': {
      id: '/_layout/docs/problems/most-common-word'
      path: '/problems/most-common-word'
      fullPath: '/docs/problems/most-common-word'
      preLoaderRoute: typeof LayoutDocsProblemsMostCommonWordRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/missing-number': {
      id: '/_layout/docs/problems/missing-number'
      path: '/problems/missing-number'
      fullPath: '/docs/problems/missing-number'
      preLoaderRoute: typeof LayoutDocsProblemsMissingNumberRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/merge-sorted-array': {
      id: '/_layout/docs/problems/merge-sorted-array'
      path: '/problems/merge-sorted-array'
      fullPath: '/docs/problems/merge-sorted-array'
      preLoaderRoute: typeof LayoutDocsProblemsMergeSortedArrayRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/longest-palindrome': {
      id: '/_layout/docs/problems/longest-palindrome'
      path: '/problems/longest-palindrome'
      fullPath: '/docs/problems/longest-palindrome'
      preLoaderRoute: typeof LayoutDocsProblemsLongestPalindromeRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/longest-consecutive-sequence': {
      id: '/_layout/docs/problems/longest-consecutive-sequence'
      path: '/problems/longest-consecutive-sequence'
      fullPath: '/docs/problems/longest-consecutive-sequence'
      preLoaderRoute: typeof LayoutDocsProblemsLongestConsecutiveSequenceRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/implement-stack-using-queues': {
      id: '/_layout/docs/problems/implement-stack-using-queues'
      path: '/problems/implement-stack-using-queues'
      fullPath: '/docs/problems/implement-stack-using-queues'
      preLoaderRoute: typeof LayoutDocsProblemsImplementStackUsingQueuesRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/find-the-difference-of-two-arrays': {
      id: '/_layout/docs/problems/find-the-difference-of-two-arrays'
      path: '/problems/find-the-difference-of-two-arrays'
      fullPath: '/docs/problems/find-the-difference-of-two-arrays'
      preLoaderRoute: typeof LayoutDocsProblemsFindTheDifferenceOfTwoArraysRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/find-the-difference': {
      id: '/_layout/docs/problems/find-the-difference'
      path: '/problems/find-the-difference'
      fullPath: '/docs/problems/find-the-difference'
      preLoaderRoute: typeof LayoutDocsProblemsFindTheDifferenceRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/find-all-numbers-disappeared-in-an-array': {
      id: '/_layout/docs/problems/find-all-numbers-disappeared-in-an-array'
      path: '/problems/find-all-numbers-disappeared-in-an-array'
      fullPath: '/docs/problems/find-all-numbers-disappeared-in-an-array'
      preLoaderRoute: typeof LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/find-all-duplicates-in-an-array': {
      id: '/_layout/docs/problems/find-all-duplicates-in-an-array'
      path: '/problems/find-all-duplicates-in-an-array'
      fullPath: '/docs/problems/find-all-duplicates-in-an-array'
      preLoaderRoute: typeof LayoutDocsProblemsFindAllDuplicatesInAnArrayRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/distribute-candies': {
      id: '/_layout/docs/problems/distribute-candies'
      path: '/problems/distribute-candies'
      fullPath: '/docs/problems/distribute-candies'
      preLoaderRoute: typeof LayoutDocsProblemsDistributeCandiesRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/determine-if-two-strings-are-close': {
      id: '/_layout/docs/problems/determine-if-two-strings-are-close'
      path: '/problems/determine-if-two-strings-are-close'
      fullPath: '/docs/problems/determine-if-two-strings-are-close'
      preLoaderRoute: typeof LayoutDocsProblemsDetermineIfTwoStringsAreCloseRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/contains-duplicate': {
      id: '/_layout/docs/problems/contains-duplicate'
      path: '/problems/contains-duplicate'
      fullPath: '/docs/problems/contains-duplicate'
      preLoaderRoute: typeof LayoutDocsProblemsContainsDuplicateRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': {
      id: '/_layout/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
      path: '/problems/check-if-number-has-equal-digit-count-and-digit-value'
      fullPath: '/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
      preLoaderRoute: typeof LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/best-time-to-buy-and-sell-stock': {
      id: '/_layout/docs/problems/best-time-to-buy-and-sell-stock'
      path: '/problems/best-time-to-buy-and-sell-stock'
      fullPath: '/docs/problems/best-time-to-buy-and-sell-stock'
      preLoaderRoute: typeof LayoutDocsProblemsBestTimeToBuyAndSellStockRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/problems/asteroid-collision': {
      id: '/_layout/docs/problems/asteroid-collision'
      path: '/problems/asteroid-collision'
      fullPath: '/docs/problems/asteroid-collision'
      preLoaderRoute: typeof LayoutDocsProblemsAsteroidCollisionRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/': {
      id: '/_layout/docs/leetcode75/arrays-strings/'
      path: '/leetcode75/arrays-strings'
      fullPath: '/docs/leetcode75/arrays-strings'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsIndexRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/string-compression': {
      id: '/_layout/docs/leetcode75/arrays-strings/string-compression'
      path: '/leetcode75/arrays-strings/string-compression'
      fullPath: '/docs/leetcode75/arrays-strings/string-compression'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsStringCompressionRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/product-of-array-except-self': {
      id: '/_layout/docs/leetcode75/arrays-strings/product-of-array-except-self'
      path: '/leetcode75/arrays-strings/product-of-array-except-self'
      fullPath: '/docs/leetcode75/arrays-strings/product-of-array-except-self'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/merge-strings-alternately': {
      id: '/_layout/docs/leetcode75/arrays-strings/merge-strings-alternately'
      path: '/leetcode75/arrays-strings/merge-strings-alternately'
      fullPath: '/docs/leetcode75/arrays-strings/merge-strings-alternately'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/kids-with-greatest-candies': {
      id: '/_layout/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
      path: '/leetcode75/arrays-strings/kids-with-greatest-candies'
      fullPath: '/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/introduction': {
      id: '/_layout/docs/leetcode75/arrays-strings/introduction'
      path: '/leetcode75/arrays-strings/introduction'
      fullPath: '/docs/leetcode75/arrays-strings/introduction'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsIntroductionRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': {
      id: '/_layout/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
      path: '/leetcode75/arrays-strings/increasing-triplet-subsequence'
      fullPath: '/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
    '/_layout/docs/leetcode75/arrays-strings/gcd-of-strings': {
      id: '/_layout/docs/leetcode75/arrays-strings/gcd-of-strings'
      path: '/leetcode75/arrays-strings/gcd-of-strings'
      fullPath: '/docs/leetcode75/arrays-strings/gcd-of-strings'
      preLoaderRoute: typeof LayoutDocsLeetcode75ArraysStringsGcdOfStringsRouteImport
      parentRoute: typeof LayoutDocsRoute
    }
  }
}

interface LayoutDocsRouteChildren {
  LayoutDocsLayoutRoute: typeof LayoutDocsLayoutRoute
  LayoutDocsIndexRoute: typeof LayoutDocsIndexRoute
  LayoutDocsProblemsAsteroidCollisionRoute: typeof LayoutDocsProblemsAsteroidCollisionRoute
  LayoutDocsProblemsBestTimeToBuyAndSellStockRoute: typeof LayoutDocsProblemsBestTimeToBuyAndSellStockRoute
  LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute: typeof LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  LayoutDocsProblemsContainsDuplicateRoute: typeof LayoutDocsProblemsContainsDuplicateRoute
  LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute: typeof LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute
  LayoutDocsProblemsDistributeCandiesRoute: typeof LayoutDocsProblemsDistributeCandiesRoute
  LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute: typeof LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute
  LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute: typeof LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  LayoutDocsProblemsFindTheDifferenceRoute: typeof LayoutDocsProblemsFindTheDifferenceRoute
  LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute: typeof LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute
  LayoutDocsProblemsImplementStackUsingQueuesRoute: typeof LayoutDocsProblemsImplementStackUsingQueuesRoute
  LayoutDocsProblemsLongestConsecutiveSequenceRoute: typeof LayoutDocsProblemsLongestConsecutiveSequenceRoute
  LayoutDocsProblemsLongestPalindromeRoute: typeof LayoutDocsProblemsLongestPalindromeRoute
  LayoutDocsProblemsMergeSortedArrayRoute: typeof LayoutDocsProblemsMergeSortedArrayRoute
  LayoutDocsProblemsMissingNumberRoute: typeof LayoutDocsProblemsMissingNumberRoute
  LayoutDocsProblemsMostCommonWordRoute: typeof LayoutDocsProblemsMostCommonWordRoute
  LayoutDocsProblemsNumberOf1BitsRoute: typeof LayoutDocsProblemsNumberOf1BitsRoute
  LayoutDocsProblemsNumberOfGoodPairsRoute: typeof LayoutDocsProblemsNumberOfGoodPairsRoute
  LayoutDocsProblemsTwoSumRoute: typeof LayoutDocsProblemsTwoSumRoute
  LayoutDocsProblemsUniqueNumberOfOccurrencesRoute: typeof LayoutDocsProblemsUniqueNumberOfOccurrencesRoute
  LayoutDocsProblemsValidParenthesesRoute: typeof LayoutDocsProblemsValidParenthesesRoute
  LayoutDocsIntroductionIndexRoute: typeof LayoutDocsIntroductionIndexRoute
  LayoutDocsLeetcode75IndexRoute: typeof LayoutDocsLeetcode75IndexRoute
  LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute: typeof LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute
  LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute: typeof LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  LayoutDocsLeetcode75ArraysStringsIntroductionRoute: typeof LayoutDocsLeetcode75ArraysStringsIntroductionRoute
  LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute: typeof LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute: typeof LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute: typeof LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  LayoutDocsLeetcode75ArraysStringsStringCompressionRoute: typeof LayoutDocsLeetcode75ArraysStringsStringCompressionRoute
  LayoutDocsLeetcode75ArraysStringsIndexRoute: typeof LayoutDocsLeetcode75ArraysStringsIndexRoute
}

const LayoutDocsRouteChildren: LayoutDocsRouteChildren = {
  LayoutDocsLayoutRoute: LayoutDocsLayoutRoute,
  LayoutDocsIndexRoute: LayoutDocsIndexRoute,
  LayoutDocsProblemsAsteroidCollisionRoute:
    LayoutDocsProblemsAsteroidCollisionRoute,
  LayoutDocsProblemsBestTimeToBuyAndSellStockRoute:
    LayoutDocsProblemsBestTimeToBuyAndSellStockRoute,
  LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute:
    LayoutDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute,
  LayoutDocsProblemsContainsDuplicateRoute:
    LayoutDocsProblemsContainsDuplicateRoute,
  LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute:
    LayoutDocsProblemsDetermineIfTwoStringsAreCloseRoute,
  LayoutDocsProblemsDistributeCandiesRoute:
    LayoutDocsProblemsDistributeCandiesRoute,
  LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute:
    LayoutDocsProblemsFindAllDuplicatesInAnArrayRoute,
  LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute:
    LayoutDocsProblemsFindAllNumbersDisappearedInAnArrayRoute,
  LayoutDocsProblemsFindTheDifferenceRoute:
    LayoutDocsProblemsFindTheDifferenceRoute,
  LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute:
    LayoutDocsProblemsFindTheDifferenceOfTwoArraysRoute,
  LayoutDocsProblemsImplementStackUsingQueuesRoute:
    LayoutDocsProblemsImplementStackUsingQueuesRoute,
  LayoutDocsProblemsLongestConsecutiveSequenceRoute:
    LayoutDocsProblemsLongestConsecutiveSequenceRoute,
  LayoutDocsProblemsLongestPalindromeRoute:
    LayoutDocsProblemsLongestPalindromeRoute,
  LayoutDocsProblemsMergeSortedArrayRoute:
    LayoutDocsProblemsMergeSortedArrayRoute,
  LayoutDocsProblemsMissingNumberRoute: LayoutDocsProblemsMissingNumberRoute,
  LayoutDocsProblemsMostCommonWordRoute: LayoutDocsProblemsMostCommonWordRoute,
  LayoutDocsProblemsNumberOf1BitsRoute: LayoutDocsProblemsNumberOf1BitsRoute,
  LayoutDocsProblemsNumberOfGoodPairsRoute:
    LayoutDocsProblemsNumberOfGoodPairsRoute,
  LayoutDocsProblemsTwoSumRoute: LayoutDocsProblemsTwoSumRoute,
  LayoutDocsProblemsUniqueNumberOfOccurrencesRoute:
    LayoutDocsProblemsUniqueNumberOfOccurrencesRoute,
  LayoutDocsProblemsValidParenthesesRoute:
    LayoutDocsProblemsValidParenthesesRoute,
  LayoutDocsIntroductionIndexRoute: LayoutDocsIntroductionIndexRoute,
  LayoutDocsLeetcode75IndexRoute: LayoutDocsLeetcode75IndexRoute,
  LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute:
    LayoutDocsLeetcode75ArraysStringsGcdOfStringsRoute,
  LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute:
    LayoutDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute,
  LayoutDocsLeetcode75ArraysStringsIntroductionRoute:
    LayoutDocsLeetcode75ArraysStringsIntroductionRoute,
  LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute:
    LayoutDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute,
  LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute:
    LayoutDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute,
  LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute:
    LayoutDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute,
  LayoutDocsLeetcode75ArraysStringsStringCompressionRoute:
    LayoutDocsLeetcode75ArraysStringsStringCompressionRoute,
  LayoutDocsLeetcode75ArraysStringsIndexRoute:
    LayoutDocsLeetcode75ArraysStringsIndexRoute,
}

const LayoutDocsRouteWithChildren = LayoutDocsRoute._addFileChildren(
  LayoutDocsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutDocsRoute: typeof LayoutDocsRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDocsRoute: LayoutDocsRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
